import "@/style/globals.css"
import Head from "next/head"

export const metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
}

interface LayoutProps {
   children: React.ReactNode
}

export default function RootLayout({ children }: LayoutProps) {
   return (
      <html lang="pt-BR">
         <Head>
            <meta
               http-equiv="Content-Security-Policy"
               content="upgrade-insecure-requests"
            />
            <title>Kintó</title>
         </Head>
         <body>{children}</body>
      </html>
   )
}
